// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/types/txBlock.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	crypto "github.com/tendermint/tendermint/proto/tendermint/crypto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PoHBlock struct {
	Height        int64           `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	PoHTimestamps []*PoHTimestamp `protobuf:"bytes,2,rep,name=poHTimestamps,proto3" json:"poHTimestamps,omitempty"`
	Signature     []byte          `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Address       []byte          `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *PoHBlock) Reset()         { *m = PoHBlock{} }
func (m *PoHBlock) String() string { return proto.CompactTextString(m) }
func (*PoHBlock) ProtoMessage()    {}
func (*PoHBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a99439714e6ae8, []int{0}
}
func (m *PoHBlock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoHBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoHBlock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoHBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoHBlock.Merge(m, src)
}
func (m *PoHBlock) XXX_Size() int {
	return m.Size()
}
func (m *PoHBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_PoHBlock.DiscardUnknown(m)
}

var xxx_messageInfo_PoHBlock proto.InternalMessageInfo

func (m *PoHBlock) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PoHBlock) GetPoHTimestamps() []*PoHTimestamp {
	if m != nil {
		return m.PoHTimestamps
	}
	return nil
}

func (m *PoHBlock) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *PoHBlock) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type PoHBlockPart struct {
	Height int64         `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Total  uint32        `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Index  uint32        `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Bytes  []byte        `protobuf:"bytes,4,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Proof  *crypto.Proof `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (m *PoHBlockPart) Reset()         { *m = PoHBlockPart{} }
func (m *PoHBlockPart) String() string { return proto.CompactTextString(m) }
func (*PoHBlockPart) ProtoMessage()    {}
func (*PoHBlockPart) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a99439714e6ae8, []int{1}
}
func (m *PoHBlockPart) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoHBlockPart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoHBlockPart.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoHBlockPart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoHBlockPart.Merge(m, src)
}
func (m *PoHBlockPart) XXX_Size() int {
	return m.Size()
}
func (m *PoHBlockPart) XXX_DiscardUnknown() {
	xxx_messageInfo_PoHBlockPart.DiscardUnknown(m)
}

var xxx_messageInfo_PoHBlockPart proto.InternalMessageInfo

func (m *PoHBlockPart) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PoHBlockPart) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PoHBlockPart) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *PoHBlockPart) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *PoHBlockPart) GetProof() *crypto.Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func init() {
	proto.RegisterType((*PoHBlock)(nil), "tendermint.types.PoHBlock")
	proto.RegisterType((*PoHBlockPart)(nil), "tendermint.types.PoHBlockPart")
}

func init() { proto.RegisterFile("tendermint/types/txBlock.proto", fileDescriptor_09a99439714e6ae8) }

var fileDescriptor_09a99439714e6ae8 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x41, 0x4f, 0x32, 0x31,
	0x14, 0xa4, 0xf0, 0xc1, 0xa7, 0x05, 0x12, 0xd3, 0x18, 0xd3, 0x10, 0x6d, 0x36, 0x9c, 0xf6, 0xd4,
	0x4d, 0xf0, 0xe0, 0x9d, 0x78, 0xe0, 0xb8, 0x36, 0x9e, 0xbc, 0x2d, 0x6c, 0x85, 0x46, 0x76, 0xdb,
	0xb4, 0x8f, 0x04, 0xfe, 0x85, 0x47, 0x8f, 0xfe, 0x1c, 0x8f, 0x1c, 0x3d, 0x1a, 0xf8, 0x23, 0x86,
	0x56, 0x64, 0x25, 0x7a, 0xdb, 0x99, 0x79, 0x6f, 0x67, 0x3a, 0x0f, 0x33, 0x90, 0x65, 0x2e, 0x6d,
	0xa1, 0x4a, 0x48, 0x60, 0x65, 0xa4, 0x4b, 0x60, 0x39, 0x9c, 0xeb, 0xc9, 0x13, 0x37, 0x56, 0x83,
	0x26, 0x67, 0x07, 0x9d, 0x7b, 0xbd, 0xd7, 0xff, 0x65, 0xe3, 0x5e, 0x15, 0xd2, 0x41, 0x56, 0x98,
	0xb0, 0xd5, 0xbb, 0xaa, 0xcc, 0x4c, 0xec, 0xca, 0x80, 0x4e, 0x8c, 0xd5, 0xfa, 0x31, 0xc8, 0xfd,
	0x57, 0x84, 0x4f, 0x52, 0x3d, 0xf2, 0x3e, 0xe4, 0x02, 0xb7, 0x66, 0x52, 0x4d, 0x67, 0x40, 0x51,
	0x84, 0xe2, 0x86, 0xf8, 0x42, 0xe4, 0x16, 0x77, 0x8d, 0x1e, 0x7d, 0xff, 0xd9, 0xd1, 0x7a, 0xd4,
	0x88, 0xdb, 0x03, 0xc6, 0x8f, 0x13, 0xf1, 0xb4, 0x32, 0x26, 0x7e, 0x2e, 0x91, 0x4b, 0x7c, 0xea,
	0xd4, 0xb4, 0xcc, 0x60, 0x61, 0x25, 0x6d, 0x44, 0x28, 0xee, 0x88, 0x03, 0x41, 0x28, 0xfe, 0x9f,
	0xe5, 0xb9, 0x95, 0xce, 0xd1, 0x7f, 0x5e, 0xdb, 0xc3, 0xfe, 0x0b, 0xc2, 0x9d, 0x7d, 0xc4, 0x34,
	0xb3, 0xf0, 0x67, 0xcc, 0x73, 0xdc, 0x04, 0x0d, 0xd9, 0x9c, 0xd6, 0x23, 0x14, 0x77, 0x45, 0x00,
	0x3b, 0x56, 0x95, 0xb9, 0x5c, 0x7a, 0xcb, 0xae, 0x08, 0x60, 0xc7, 0x8e, 0x57, 0x20, 0xf7, 0x66,
	0x01, 0x10, 0x8e, 0x9b, 0xbe, 0x1c, 0xda, 0x8c, 0x50, 0xdc, 0x1e, 0xd0, 0xea, 0x03, 0x43, 0x79,
	0x3c, 0xdd, 0xe9, 0x22, 0x8c, 0x0d, 0xef, 0xde, 0x36, 0x0c, 0xad, 0x37, 0x0c, 0x7d, 0x6c, 0x18,
	0x7a, 0xde, 0xb2, 0xda, 0x7a, 0xcb, 0x6a, 0xef, 0x5b, 0x56, 0x7b, 0xb8, 0x99, 0x2a, 0x98, 0x2d,
	0xc6, 0x7c, 0xa2, 0x8b, 0xa4, 0x7a, 0xa5, 0xc3, 0xa7, 0xef, 0x3f, 0x39, 0xbe, 0xe0, 0xb8, 0xe5,
	0xf9, 0xeb, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x5f, 0x81, 0xe7, 0x0e, 0x02, 0x00, 0x00,
}

func (m *PoHBlock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoHBlock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoHBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTxBlock(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTxBlock(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PoHTimestamps) > 0 {
		for iNdEx := len(m.PoHTimestamps) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PoHTimestamps[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTxBlock(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Height != 0 {
		i = encodeVarintTxBlock(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PoHBlockPart) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoHBlockPart) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoHBlockPart) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Proof != nil {
		{
			size, err := m.Proof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTxBlock(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Bytes) > 0 {
		i -= len(m.Bytes)
		copy(dAtA[i:], m.Bytes)
		i = encodeVarintTxBlock(dAtA, i, uint64(len(m.Bytes)))
		i--
		dAtA[i] = 0x22
	}
	if m.Index != 0 {
		i = encodeVarintTxBlock(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x18
	}
	if m.Total != 0 {
		i = encodeVarintTxBlock(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x10
	}
	if m.Height != 0 {
		i = encodeVarintTxBlock(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTxBlock(dAtA []byte, offset int, v uint64) int {
	offset -= sovTxBlock(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PoHBlock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovTxBlock(uint64(m.Height))
	}
	if len(m.PoHTimestamps) > 0 {
		for _, e := range m.PoHTimestamps {
			l = e.Size()
			n += 1 + l + sovTxBlock(uint64(l))
		}
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTxBlock(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTxBlock(uint64(l))
	}
	return n
}

func (m *PoHBlockPart) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovTxBlock(uint64(m.Height))
	}
	if m.Total != 0 {
		n += 1 + sovTxBlock(uint64(m.Total))
	}
	if m.Index != 0 {
		n += 1 + sovTxBlock(uint64(m.Index))
	}
	l = len(m.Bytes)
	if l > 0 {
		n += 1 + l + sovTxBlock(uint64(l))
	}
	if m.Proof != nil {
		l = m.Proof.Size()
		n += 1 + l + sovTxBlock(uint64(l))
	}
	return n
}

func sovTxBlock(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTxBlock(x uint64) (n int) {
	return sovTxBlock(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PoHBlock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTxBlock
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoHBlock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoHBlock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoHTimestamps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTxBlock
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTxBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoHTimestamps = append(m.PoHTimestamps, &PoHTimestamp{})
			if err := m.PoHTimestamps[len(m.PoHTimestamps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTxBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTxBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTxBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTxBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = append(m.Address[:0], dAtA[iNdEx:postIndex]...)
			if m.Address == nil {
				m.Address = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTxBlock(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTxBlock
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoHBlockPart) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTxBlock
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoHBlockPart: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoHBlockPart: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bytes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTxBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTxBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bytes = append(m.Bytes[:0], dAtA[iNdEx:postIndex]...)
			if m.Bytes == nil {
				m.Bytes = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTxBlock
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTxBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Proof == nil {
				m.Proof = &crypto.Proof{}
			}
			if err := m.Proof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTxBlock(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTxBlock
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTxBlock(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTxBlock
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTxBlock
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTxBlock
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTxBlock
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTxBlock
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTxBlock
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTxBlock        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTxBlock          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTxBlock = fmt.Errorf("proto: unexpected end of group")
)
