name: Check Markdown links
on:
  schedule:
    - cron: '* */24 * * *'
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: creachadair/github-action-markdown-link-check@master
        with:
          folder-path: "docs"
